config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  root 'tops#index'
   resources :items ,only: :index
    resources :actives ,only: :index
     resources :reviews ,only: :index
      resources :comments ,only: :index
       resources :ones ,only: :index
end

app/models/active.rb
class Active < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commentes_controller.rb
class CommentesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/ones_controller.rb
class OnesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentes_helper.rb
module CommentesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ones_helper.rb
module OnesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/actives/index.html.erb
<div class="container mt-3">

  <!-- Button trigger modal -->

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">

        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">ログアウト</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            ...
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  
<button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="ご確認ください" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>

<nav id="navbar-example2" class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" href="#fat">@fat</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#mdo">@mdo</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#one">one</a>
        <a class="dropdown-item" href="#two">two</a>
        <div role="separator" class="dropdown-divider"></div>
        <a class="dropdown-item" href="#three">three</a>
      </div>
    </li>
  </ul>
</nav>
<div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
  <h4 id="fat">@fat</h4>
  <p>...........................................</p>
  <h4 id="mdo">@mdo</h4>
  <p>...</p>
  <h4 id="one">one</h4>
  <p>...</p>
  <h4 id="two">two</h4>
  <p>...</p>
  <h4 id="three">three</h4>
  <p>...</p>
</div>

<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <svg class="bd-placeholder-img rounded mr-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#007aff"/></svg>
    <strong class="mr-auto">Bootstrap</strong>
    <small>11 mins ago</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    Hello, world! This is a toast message.
  </div>
</div>

<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
  Tooltip on top
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">
  Tooltip on bottom
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
  Tooltip on left
</button>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->



</div>    

app/views/comments/index.html.erb
<style>
  .box{
    width: 100px;
    height: 100px;
    color: white;
    padding: 5px
  }
</style>

<body>
<div class="box bg-secondary">1</div>
<div class="box bg-primary">2</div>
<div class="box bg-red">3</div>
</body>

app/views/items/index.htm.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
<div class="container mt-5">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div class="jumbotron">
    <h1 class="display-3">自分を叶えよう</h1>
    <p class="lead">自分の行動を見直す</p>
    <hr class="my-2">
    <p>It uses utility classes for typography and
       spacing to space content out within the larger container.</p>
    <p class="lead">
      <button type="button" class="btn btn-outline-success">Success</button>
    </p>
  </div>
  <button type="button" class="btn btn-success">Success</button>
  


</div>  
</body>

</html>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
<div class="container mt-5">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div class="jumbotron">
    <h1 class="display-3">自分を叶えよう</h1>
    <p class="lead">自分の行動を見直す</p>
    <hr class="my-2">
    <p>It uses utility classes for typography and
       spacing to space content out within the larger container.</p>
    <p class="lead">
      <button type="button" class="btn btn-outline-success">Success</button>
    </p>
  </div>
  <button type="button" class="btn btn-success">Success</button>
  


</div>  
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootLesson</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      
  </head>

  <body>
    <%= yield %>
  <div class="list-group">
    <%= link_to "トップページ",root_path, class: "list-group-item" %>
    <%= link_to "アイテム",items_path, class: "list-group-item" %>
    <%= link_to "行動"    ,actives_path, class: "list-group-item" %>
    <%= link_to "反省"    ,reviews_path, class: "list-group-item" %>
    <%= link_to "フォーム"    ,ones_path, class: "list-group-item" %>
    <%= link_to "コメント"    ,comments_path, class: "list-group-item" %>
  </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<script>
$(function () {
  $('[data-toggle="popover"]').popover()
});
</script>

<script>
$(function () {
   $('[data-toggle="tooltip"]').tooltip()
});
</script>

  </body>

  
</html>

app/views/ones/index.html.erb
<div class="container my-5">
  
  <form class="needs-validation" action="" method="post" novalidate>
    
    <div class="form-group">
      <label for="myname">お名前</label>
      <input class="form-control" type="text" name="myname" id="myname" required>
    </div>

    <button type="submit">送信</button>

  </form>

 <form action="" method="post">

    <div class="form-check">
      <input class="form-check-input" type="checkbox" name="job" value="会社員" id="job_1">
       <label class="form-check-label" for="job_1">会社員</label>
    </div>
    <div class="form-check">
       <input type="form-check-input" name="job" value="自営業" id="job_2">
       <label class="form-check-label" for="job_2">自営業員</label>
    </div>
    <div class="form-check">
      <input type="form-check-input" name="job" value="役員" id="job_3">
       <label class="form-check-label" for="job_3">役員</label>
    </div>
</form>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>

<form>
  <div class="form-group">
    <label for="formControlRange">Example Range input</label>
    <input type="range" class="form-control-range" id="formControlRange">
  </div>
</form>

</form>

























</div>

app/views/reviews/index.html.erb
<body>
 <div class="container mt-5">
  <div class= "shadow p-3 mb-5 bg-dark rounded border border-info"></div>
  </div>

  <button type="button" class="close" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
<div class= "d-none d-md-block shadow p-3 mb-5 bg-danger rounded border border-info"></div>
</div>
 </div>  

<div class="d-inline p-2 bg-primary text-white">d-inline</div>
<div class="d-inline p-2 bg-dark text-white">d-inline</div>
<span class="d-block p-2 bg-primary text-white">d-block</span>
<span class="d-block p-2 bg-dark text-white">d-block</span>
<div class="d-flex p-2 bd-highlight">I'm a flexbox container!</div>
<div class="d-inline-flex p-2 bd-highlight">I'm an inline flexbox container!</div>

<div class="d-flex flex-row bd-highlight mb-3">
  <div class="p-2 bd-highlight">Flex item 1</div>
  <div class="p-2 bd-highlight">Flex item 2</div>
  <div class="p-2 bd-highlight">Flex item 3</div>
</div>

<div class="float-left">Float left on all viewport sizes</div><br>
<div class="float-right">Float right on all viewport sizes</div><br>
<div class="float-none">Don't float on all viewport sizes</div>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
</div>

<h1 class="text-hide" style="background-image: url('/docs/4.5/assets/brand/bootstrap-solid.svg'); width: 50px; height: 50px;">Bootstrap</h1>

<div class="bg-info clearfix">
  <button type="button" class="btn btn-secondary float-left">Example Button floated left</button>
  <button type="button" class="btn btn-secondary float-right">Example Button floated right</button>
</div>

<table style="height: 100px;">
  <tbody>
    <tr>
      <td class="align-baseline">baseline</td>
      <td class="align-top">top</td>
      <td class="align-middle">middle</td>
      <td class="align-bottom">bottom</td>
      <td class="align-text-top">text-top</td>
      <td class="align-text-bottom">text-bottom</td>
    </tr>
  </tbody>
</table>

<div class="overflow-auto">...</div>
<div class="overflow-hidden">...</div>

<div class ="container bg-white d-flex justify-content-start">
  <div class="box2 bg-secondary">1</div>
  <div class="box2 bg-primary">2</div>
  <div class="box2 bg-red">3</div>
</div>
</body>

app/views/tops/index.html.erb
<style>
.title{
  /* background-color:#f99; */
}
.box1{
  background-color: bisque;
}
.box2{
  background-color: darkkhaki;
}
.box3{
  background-color: red;
}
</style>

<body>
  
  <div class="container"> 
    <div class="title row">  
      <h1 class="mt-5 pb-5">Hello,Bootstrap!</h1>
    </div>

    <div class="row">
    <div class ="box1 col-3">box1</div>
    <div class ="box2 col-7">box2</div>
    <div class ="box3 col-2">box3</div>
    </div>
    <div class="row">
      <div class ="box1 col-3 offset-2">box1</div>
      <div class ="box2 col-7">box2</div>
    </div>

  <table class="table table-hover">
  <thead>
    <tr>
      <th>目標</th>
      <th>First Name</th>
      <th>Last Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
    </tr>
  </tbody>

</table>

<p>HTMLの段落は<code>p</code>で表現します<p>
<p>HTMLの段落は<kbd>p</kbd>で表現します<p>

 <pre><code>
  def name(int)
   p int
  end

  name("inamura")
 </code><pre>

<img class= "img-fluid" src="https://picsum.photos/40/30">

</body>
</html>